namespace EawModinfo.Utilities
{
    internal static class ModinfoJsonSchema
    {
        public const string Schema = @"{
  ""$id"":""https://AlamoEngine-Tools.github.com/eaw.modinfo.json"",
  ""$schema"":""https://json-schema.org/draft/2020-12/schema"",
  ""description"":""A standard definition for Star Wars: Empire at War mod info files."",
  ""title"":""EaW Modinfo"",
  ""type"":""object"",
  ""$defs"":{
    ""modref"":{
      ""type"":""object"",
      ""required"":[
        ""modtype"",
        ""identifier""
      ],
      ""properties"":{
        ""modtype"":{
          ""type"":""number"",
          ""minimum"":0,
          ""maximum"":2
        },
        ""identifier"":{
          ""type"":""string""
        },
        ""version-range"":{
          ""type"":""string""
        }
      },
      ""additionalProperties"":false
    },
    ""languageinfo"":{
      ""required"":[
        ""code""
      ],
      ""properties"":{
        ""code"":{
          ""type"":""string"",
          ""minLength"":2,
          ""maxLength"":2
        },
        ""support"":{
          ""type"":""number"",
          ""minimum"":1,
          ""maximum"":7
        }
      }
    },
    ""steamdata"":{
      ""type"":""object"",
      ""required"":[
        ""publishedfileid"",
        ""contentfolder"",
        ""visibility"",
        ""title""
      ],
      ""properties"":{
        ""publishedfileid"":{
          ""type"":""string""
        },
        ""contentfolder"":{
          ""type"":""string""
        },
        ""visibility"":{
          ""type"":""integer"",
          ""minimum"":0,
          ""maximum"":3
        },
        ""title"":{
          ""type"":""string""
        },
        ""metadata"":{
          ""type"":""string""
        },
        ""tags"":{
          ""type"":""array"",
          ""uniqueItems"":true,
          ""minItems"":1,
          ""items"":{
            ""type"":""string""
          },
          ""contains"":{
            ""oneOf"":[
              {
                ""const"":""FOC""
              },
              {
                ""const"":""EAW""
              }
            ]
          }
        },
        ""previewfile"":{
          ""type"":""string""
        },
        ""description"":{
          ""type"":""string""
        }
      }
    }
  },
  ""properties"":{
    ""name"":{
      ""type"":""string""
    },
    ""summary"":{
      ""type"":""string""
    },
    ""icon"":{
      ""type"":""string""
    },
    ""version"":{
      ""type"":""string"",
      ""description"":""No validation for the version string as implementations can verify this better than JSON schemas. ""
    },
    ""dependencies"":{
      ""type"":""array"",
      ""contains"":{
        ""$ref"":""#/$defs/modref""
      },
      ""items"":[
        {
          ""oneOf"":[
            {
              ""enum"":[
                ""ResolveRecursive"",
                ""ResolveLastItem"",
                ""FullResolved""
              ]
            },
            {
              ""$ref"":""#/$defs/modref""
            }
          ]
        },
        {
          ""$ref"":""#/$defs/modref""
        }
      ]
    },
    ""languages"":{
      ""type"":""array"",
      ""items"":{
        ""$ref"":""#/$defs/languageinfo""
      }
    },
    ""steamdata"":{
      ""$ref"":""#/$defs/steamdata""
    },
    ""custom"":{
      ""type"":""array"",
      ""uniqueItems"":true
    }
  },
  ""required"":[
    ""name""
  ]
}";
    }
}