name: EaW Modinfo Implementation Build & Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-test:
    name: Build & Test
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [Debug, Release]
        dotnet-framework: [5.0.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-framework }}
    - name: Build
      run: dotnet build src/EawModinfo/EawModinfo.csproj -f net5.0
    - name: Unit Test
      run: dotnet test src/EawModinfo.Tests/EawModinfo.Tests.csproj -f net5.0
      env:
        Configuration: ${{ matrix.configuration }}
